# Generated by Django 4.2.2 on 2023-07-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='inventory', to='rpgbot.item', verbose_name='inventory'),
        ),
    ]
