# Generated by Django 4.2.2 on 2023-06-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, verbose_name='player ID'),
        ),
    ]
