# Generated by Django 4.2.2 on 2023-06-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0002_remove_player_id_player_player_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('Warrior', 'Warrior'), ('Rogue', 'Rogue'), ('Mage', 'Mage')], max_length=50, verbose_name='class_type')),
            ],
            options={
                'verbose_name': 'characterClass',
                'verbose_name_plural': 'characterClasss',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='player_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='player ID'),
        ),
        migrations.AddField(
            model_name='player',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='rpgbot.characterclass', verbose_name='Character class'),
        ),
    ]
