# Generated by Django 4.2.2 on 2023-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0003_characterclass_alter_player_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='discord_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='discord_name'),
        ),
    ]
