# Generated by Django 4.2.2 on 2023-07-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0003_item_price_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='name',
            new_name='wtf',
        ),
    ]
