# Generated by Django 4.2.2 on 2023-07-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0004_rename_name_shop_wtf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='wtf',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='items',
        ),
    ]
