# Generated by Django 4.2.2 on 2023-06-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0004_player_discord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='class_images', verbose_name='character_image'),
        ),
    ]
