# Generated by Django 4.2.2 on 2023-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0005_rename_wtf_shop_name_remove_shop_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='items',
            field=models.ManyToManyField(to='rpgbot.item', verbose_name='items'),
        ),
    ]
