# Generated by Django 4.2.2 on 2023-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0006_player_attack_player_current_health_player_defense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('max_health', models.IntegerField(default=0, verbose_name='max_health')),
                ('current_health', models.IntegerField(default=0, verbose_name='current_health')),
                ('attack', models.IntegerField(default=0, verbose_name='attack')),
                ('defense', models.IntegerField(default=0, verbose_name='defense')),
                ('image', models.ImageField(blank=True, null=True, upload_to='enemy_images', verbose_name='image')),
            ],
            options={
                'verbose_name': 'enemy',
                'verbose_name_plural': 'enemies',
            },
        ),
        migrations.RemoveField(
            model_name='characterclass',
            name='images',
        ),
        migrations.AddField(
            model_name='characterclass',
            name='attack',
            field=models.IntegerField(default=0, verbose_name='attack'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='defense',
            field=models.IntegerField(default=0, verbose_name='defense'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='health',
            field=models.IntegerField(default=0, verbose_name='health'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class_images', verbose_name='image'),
        ),
    ]
