# Generated by Django 4.2.2 on 2023-06-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0007_enemy_remove_characterclass_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='description')),
                ('enemy', models.ManyToManyField(blank=True, null=True, to='rpgbot.enemy', verbose_name='enemies')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='rpgbot.location', verbose_name='location'),
        ),
    ]
