# Generated by Django 4.2.2 on 2023-07-16 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0007_iteminstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='players', to='rpgbot.iteminstance', verbose_name='inventory'),
        ),
    ]
