# Generated by Django 4.2.2 on 2023-07-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0008_alter_player_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminstance',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
