# Generated by Django 4.2.2 on 2023-06-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0008_location_player_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='enemy',
            field=models.ManyToManyField(blank=True, to='rpgbot.enemy', verbose_name='enemies'),
        ),
    ]
