# Generated by Django 4.2.2 on 2023-07-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0009_alter_iteminstance_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='equipped_amulet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_amulet', to='rpgbot.iteminstance', verbose_name='equipped_amulet'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_body_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_body_armour', to='rpgbot.iteminstance', verbose_name='equipped_body_armour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_helmet', to='rpgbot.iteminstance', verbose_name='equipped_helmet'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_leg_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_leg_armor', to='rpgbot.iteminstance', verbose_name='equipped_leg_armor'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_ring1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring1', to='rpgbot.iteminstance', verbose_name='equipped_ring1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_ring2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring2', to='rpgbot.iteminstance', verbose_name='equipped_ring2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon', to='rpgbot.iteminstance', verbose_name='equipped_weapon'),
        ),
    ]
