# Generated by Django 4.2.2 on 2023-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0009_alter_location_enemy'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='experience'),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='player',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='experience'),
        ),
        migrations.AlterField(
            model_name='player',
            name='attack',
            field=models.IntegerField(default=0, verbose_name='attack'),
        ),
        migrations.AlterField(
            model_name='player',
            name='defense',
            field=models.IntegerField(default=0, verbose_name='defense'),
        ),
    ]
