# Generated by Django 4.2.2 on 2023-06-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0010_enemy_level_enemy_xp_player_level_player_xp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='xp',
            field=models.IntegerField(default=10, verbose_name='experience'),
        ),
    ]
