# Generated by Django 4.2.2 on 2023-06-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0011_alter_enemy_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyInstances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy', to='rpgbot.enemy', verbose_name='enemy')),
            ],
            options={
                'verbose_name': 'enemyInstances',
                'verbose_name_plural': 'enemyInstancess',
            },
        ),
    ]
