# Generated by Django 4.2.2 on 2023-07-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0012_enemyinstances'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='victory_message',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='victory_message'),
        ),
    ]
