# Generated by Django 4.2.2 on 2023-07-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0017_enemy_gold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.CharField(choices=[('Weapon', 'Weapon'), ('Body Armor', 'Body Armor'), ('Helmet', 'Helmet'), ('Leg Armor', 'Leg Armor'), ('Ring', 'Ring'), ('Amulet', 'Amulet'), ('Misc', 'Misc')], max_length=50, verbose_name='type')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_amulet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_amulet'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_body_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_body_armour'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_helmet'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_leg_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_leg_armor'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_ring1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_ring1'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_ring2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_ring2'),
        ),
        migrations.AddField(
            model_name='player',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rpgbot.item', verbose_name='equipped_weapon'),
        ),
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='players', to='rpgbot.item', verbose_name='inventory'),
        ),
    ]
