# Generated by Django 4.2.2 on 2023-07-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0018_item_player_equipped_amulet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='attack',
            field=models.IntegerField(default=0, verbose_name='attack'),
        ),
        migrations.AddField(
            model_name='item',
            name='defense',
            field=models.IntegerField(default=0, verbose_name='defense'),
        ),
        migrations.AddField(
            model_name='item',
            name='health',
            field=models.IntegerField(default=0, verbose_name='health'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_amulet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_amulet', to='rpgbot.item', verbose_name='equipped_amulet'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_body_armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_body_armour', to='rpgbot.item', verbose_name='equipped_body_armour'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_helmet', to='rpgbot.item', verbose_name='equipped_helmet'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_leg_armor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_leg_armor', to='rpgbot.item', verbose_name='equipped_leg_armor'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_ring1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring1', to='rpgbot.item', verbose_name='equipped_ring1'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_ring2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_ring2', to='rpgbot.item', verbose_name='equipped_ring2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='equipped_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon', to='rpgbot.item', verbose_name='equipped_weapon'),
        ),
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.ManyToManyField(blank=True, related_name='inventory', to='rpgbot.item', verbose_name='inventory'),
        ),
    ]
