# Generated by Django 4.2.2 on 2023-07-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpgbot', '0020_item_special_attributes_alter_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='drops',
            field=models.ManyToManyField(blank=True, related_name='drops', to='rpgbot.item', verbose_name='drops'),
        ),
    ]
